### ISSUE TITLE
Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

### ISSUE THREAD

**Issue by acuntex** [SierraSoftworks/Iridium#107]
There seems to be a bug when you have the following database structure:

- database1
   - users
      - _id: string
- database2
   - users
      - _id: ObjectID

There is a Core-subclass for every connection.

When you access only database1.users in one execution of the application everything works fine.
But after you accessed database2.users there is no chance to access database1.users until you restart and the following error occurs:

> Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
>     at new ObjectID (folder/node_modules/bson/lib/bson/objectid.js:50:11)
>     at Object.toDB (folder/node_modules/iridium/lib/Transforms.ts:41:46)
>     at ModelHelpers.transformToDB (folder/node_modules/iridium/lib/ModelHelpers.ts:62:33)
>     at ModelHelpers.convertToDB (folder/node_modules/iridium/lib/ModelHelpers.ts:109:21)
>     at Promise_1.Nodeify.Promise.resolve.then (folder/node_modules/iridium/lib/Model.ts:379:40)
>     at <anonymous>
>     at process._tickDomainCallback (internal/process/next_tick.js:228:7)

Is there maybe some caching for the databases?
Thanks!

**Comment by SPARTAN563** [comment]
Hey @acuntex, this sounds really odd. There isn't any caching in place at all (unless you've implemented a caching plugin), so there shouldn't be any strange interactions.

To me more specific, every time you run a query with Iridium you get a unique instance of your `Iridium.Instance` subclass, there's no instance caching and `model.findOne("a") !== model.findOne("a")` as a result. So you shouldn't be running into a situation where `db1.users.findOne(...)` affects `db2.users.findOne(...)`.

Something else worth taking into consideration is the fact that the transform throwing that error is the `ObjectID` transform (which is the default for `_id`). If you're using IDs which are not `ObjectID` based for `database1` then make sure to configure `@Property(string)` on its `_id` field to prevent any errors there. For property transforms, they will only be executed when you assign to the property as well, so that may explain the issue you're seeing (attempting to access the field for assignment).

**Comment by acuntex** [comment]
database1.users._id is configured as @Property(string)
database2.users._id is configured as @Property(ObjectID)
