### ISSUE TITLE
Recoursion error

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [SierraSoftworks/Iridium#41]
RangeError: Maximum call stack size exceeded
    at isDate (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:18:29)
    at calculateElement (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:77:42)
    at calculateObjectSize (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:37:22)
    at calculateElement (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:120:77)
    at calculateObjectSize (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:37:22)
    at calculateElement (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:120:77)
    at calculateObjectSize (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:37:22)
    at calculateElement (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:120:77)
    at calculateObjectSize (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:37:22)
    at calculateElement (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:120:77)
    at calculateObjectSize (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:37:22)
    at calculateElement (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:120:77)
    at calculateObjectSize (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:37:22)
    at calculateElement (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:120:77)
    at calculateObjectSize (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:37:22)
    at calculateElement (C:\localhost\ui-js\node_modules\bson\lib\bson\parser\calculate_size.js:120:77)

========
if i write model.add(data) and data has recoursive props, i get error

**Comment by uMaxmaxmaximus** [comment]
for a place to write your project, I speak your tester

**Comment by SPARTAN563** [comment]
Hi Ivan,

Looks like that's just the standard MongoDB BSON serializer which doesn't know how to handle recursive properties. The best solution there is to avoid using recursive properties in your documents, or use transforms to convert them into non-recursive properties prior to serialization.

**Comment by uMaxmaxmaximus** [comment]
Do not you think that this is the level of the framework and not the level of the user of the framework?

**Comment by SPARTAN563** [comment]
The tricky aspect is determining a safe strategy through which you can handle recursive documents in every use case, not something which is straightforward at all (hence the reason most serializers crash when you give them those kinds of documents). With that in mind, it's almost universally safer for the application developer (user level) to implement their own strategy for serializing those kinds of documents (since they have a much better understanding of the how and why of the recursion).

Could you give me an example of the data structure you're trying to serialize and I'll see if I have any quick suggestions?

**Comment by uMaxmaxmaximus** [comment]
example data.texture is a https://github.com/nkzawa/socket.io-stream

**Comment by SPARTAN563** [comment]
Okay, I assume initially the `data.texture` is what has self-referencing properties (which results in the recursion) and that your `Utils.saveFileByStream` is returning some ID/path of the saved file? If that's the case, my recommendation would be to call the initial property something like `textureStream` and then always call your method to transform it as part of the `onCreating` hook.
