### ISSUE TITLE
Class constructor Core cannot be invoked without 'new'

### ISSUE THREAD

**Issue by anurag-gethullo** [SierraSoftworks/Iridium#62]
Hi, i'am struggling to get it running. I have just copied the code from example/IntelliSense.ts.
my node version is -> 7.2.0,
npm version is -> 3.10.9

The complete stack trace of error is
```
/Users/anuragtiwari/Self-learning/MongoDb/iridium-test.js:66
        var _this = _super.apply(this, arguments) || this;
                           ^

TypeError: Class constructor Core cannot be invoked without 'new'
    at new MyDB (/Users/anuragtiwari/Self-learning/MongoDb/iridium-test.js:66:28)
    at Object.<anonymous> (/Users/anuragtiwari/Self-learning/MongoDb/iridium-test.js:72:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

Thanks in advance.

**Comment by anurag-gethullo** [comment]
I was running with es5 instead of es6.

**Comment by SPARTAN563** [comment]
Glad to see you got it sorted out, unfortunately ES6 classes have some rather odd restrictions regarding how their constructors are called, I've had to work around them in this project already but by far the easiest solution is to just use ES6 classes yourself.
